In [3]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (2.1.0)




[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np
import sklearn

In [6]:
df = pd.read_csv("Reddit_Data.csv")

In [7]:
df.shape

(37249, 2)

In [8]:
null_df = df.isnull().sum()

In [9]:
null_df

clean_comment    100
category           0
dtype: int64

In [12]:
df.shape

(37247, 2)

In [16]:
df.head()

clean_comment  category
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1
5  you should all sit down together and watch the...        -1

In [22]:
null_check_column = df['clean_comment'].isnull()

In [23]:
null_check_column

1        False
2        False
3        False
4        False
5        False
         ...  
37244    False
37245    False
37246    False
37247    False
37248    False
Name: clean_comment, Length: 37247, dtype: bool

In [24]:
df_clean_rows = df.dropna()

In [26]:
df_clean_rows = df.dropna(subset=['clean_comment'])

In [27]:
df_clean_rows

clean_comment  category
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
5      you should all sit down together and watch the...        -1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37147 rows x 2 columns]

In [45]:
df_clean_rows.shape

(36797, 2)

In [46]:
X = df_clean_rows['clean_comment']

In [47]:
X.shape

(36797,)

In [51]:
X.head()

1    buddhism has very much lot compatible with chr...
2    seriously don say thing first all they won get...
3    what you have learned yours and only yours wha...
4    for your own benefit you may want read living ...
5    you should all sit down together and watch the...
Name: clean_comment, dtype: object

In [48]:
y = df_clean_rows['category']

In [50]:
y.head()

1    1
2   -1
3    0
4    1
5   -1
Name: category, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(X,y,test_size =0.2, random_state = 42)

In [59]:
X_test.shape

(29437,)

In [60]:
X_train.shape

(7360,)

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_features=40000)  # Adjust the number of features as needed
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [62]:
from sklearn.linear_model import LogisticRegression

logistic_regression_model = LogisticRegression(max_iter=40000)  # You can adjust hyperparameters as needed
logistic_regression_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=40000)

In [67]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

y_pred = logistic_regression_model.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate a classification report
classification_rep = classification_report(y_test, y_pred)

# Create a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)

# Calculate the F1-score
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the metrics
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_rep)
print("\nConfusion Matrix:\n", confusion_mat)
print("\nF1 Score:", f1)

Accuracy: 0.7672656860413765

Classification Report:
               precision    recall  f1-score   support

          -1       0.80      0.46      0.59      6563
           0       0.77      0.85      0.81     10293
           1       0.76      0.86      0.81     12581

    accuracy                           0.77     29437
   macro avg       0.78      0.72      0.73     29437
weighted avg       0.77      0.77      0.76     29437


Confusion Matrix:
 [[ 3035  1342  2186]
 [  283  8720  1290]
 [  456  1294 10831]]

F1 Score: 0.7569193267252465
